try:
    print(x)
except:
    print("something went wrong")
finally:
    print("they try except is finished")
